### ISSUE TITLE
[Android] Percentage values go Integer.MAX when changing orientation

### ISSUE THREAD

**Issue by pskowronek** [rjaros87/pm-station-usb#13]
Percentage values go Integer.MAX_VALUE when changing orientation.

To reproduce:
- open app
- flip the device to horizontal position
- flip the device back to vertical - for a second or two you can see the percentage values to be set to Integer.MAX_VALUE

**Comment by rjaros87** [comment]
👍 confirm.

**Comment by sanchin** [comment]
Yeah, I know, my brother even called me with that (first Github issue I received by a phone ;D)

I'll look into that during the weekend, although it seems weird since the values get updated with read, and after the rotation they should be initialized with null / empty / zeros, same as when the app launches. What weird mathematical operation can result in MAX_VALUE? As in - division by zero (nah, exception), etc?

**Comment by pskowronek** [comment]
fixed
